# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:16

sync-via-rdme-pushapi-config:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/mos/pushapi_config_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=6238552ac90926011752e49b
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-onelink-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/OneLink/onelinkapi.yml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=624693c6fa631302dde62cf4
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-addapp-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/add-app/openapi.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=60ffdc00f71e49000fe45cad
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-raw-data-pull-api-token-v2:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/mos/raw_data_pull_api_tokenv2.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=624594011aecc40014db6e4d
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-raw-data-pull-api-token-v1:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/mos/raw_data_pull_api_tokenv1.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=62d4514efabb0500da0b2d90
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-aggregate-pull-api-v1:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/analytics/aggregate_pull_api_v1.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=62d4578cf287de0014239d8c
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-aggregate-pull-api-v2:
 script:
   - npx -y rdme@8.4.0 openapi ./docs/apis/analytics/aggregate_pull_api_v2.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=636a481d2d5ae60049dee908
 rules:
   - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-ctv-events-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/rta/ctv_events_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=624c355032911400142d1aca
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-partner-settings-api:
  script:
    - npx -y rdme@8.4.0 openapi   ./docs/apis/partnerIntSet/partner_integration_settings_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=615eb7b60319170356179796
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-engagements-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/rta/engagements_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=6203fb9db858c900490628e6
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-preload-download-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/rta/preload_download_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=6297336ccdcdd4008814970f
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-cohort-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/analytics/cohort_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=62b1be492ea1c2004f38708f
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-predict-pull-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/Predict/predict_ios_pull_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=619ca39dba52150073eae7b8
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

# sync-via-rdme-gcdapi-v5:
#   script:
#     - npx -y rdme@8.4.0 openapi ./docs/apis/gcdapi/gcdapi_v5.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=638628a899eda80f20cabab9
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-gcdapi-v4:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/gcdapi/gcdapi.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=638628a899eda80f20cabab9
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-ddlapi:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/OneLink/ddlapi.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=5f7d78862614180733ad85d7
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-adrevacctint:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/ROI360/adrevacctint.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=637632d64f5e250092a83dee
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-skan-v3-v4-schema:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/SKAD/skanv4api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=63e0f5c3a16e3d02f793ea8a
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-s2s-events:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/rta/s2s_events_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=6395db9fa17cb50068ac9e3e
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-roi360-truetax:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/ROI360/true_revenue_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=63eb8607ce3ff30366cc2b8c
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-master-api:
  script:
    - npx -y rdme@8.4.0 openapi ./docs/apis/analytics/master_api.yaml --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63 --id=63d267e835fb4100501bba5a
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

# Guides
sync-via-rdme-sdks-guides:
  script:
    - npx -y rdme@8.4.0 docs ./docs/guides/sdks/ --version=0.1 --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63  
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-deep-linking-guides:
  script:
    - npx -y rdme@8.4.0 docs ./docs/guides/deep_linking/ --version=0.1 --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63  
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

sync-via-rdme-apple-app-clips-guides:
  script:
    - npx -y rdme@8.4.0 docs ./docs/guides/apple_app_clips/ --version=0.1 --key=rdme_xn8s9h0fb20a2df26bd435f6c42b1c7d59b240b0354348510d0c2f14216e353fb8fe63  
  rules:
    - if: $CI_COMMIT_BRANCH == "master"