openapi: '3.0.3'
info:
  title: SKAN conversion mapping (CV) schema for ad networks
  version: '0.1'
security:
  - bearerAuth: []
servers:
- url: https://hq1.appsflyer.com/api/skad/conversion_schema
paths:
  /v1:
    get:
      summary: Get the CV schema for specified apps
      description: Specify one or more apps using the app ID
      operationId: get-conversion-value-mapping-schema
      parameters:
      - name: app_id
        in: query
        description: Set 0-many app IDs. If no app ID is set, the schema of all apps returns. In all other cases, the schema of the specified 
          app IDs returns.
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
               type: object
               properties:
                  data:
                     type: object
                     properties:
                        app_id:
                           type: string
                           description: "App Store app id"
                        configuration_mode:
                           type: string
                           description: "Measurment mode selected set by the advertiser" 
                        last_config_change:
                           type: string
                           description: "Time the advertiser updated the conversion value settings"
                        measurement_window: 
                           type: integer
                           description: "Activity window duration (in hours)"
                        conversion_value_mapping:
                          type: array
                          description: "Conversion values mapping"
                          items:
                            $ref: '#/components/schemas/CvMapping'
                        
              example:
                  data:
                    - app_id: id12345678
                      configuration_mode: custom_decode
                      measurement_window: 24
                      last_config_change: '2021-02-03 09:32:07.362'
                      conversion_value_mapping:
                      - conversion_value: 1
                        events:
                        - event_name: af_purchase
                          mapped_event_name: af_purchase
                          conversion_event: false
                          event_counter: 3
                          event_revenue: 5
                          min_event_counter: 3
                          max_event_counter: 6
                          min_event_revenue: 4.001
                          max_event_revenue: 5
                          event_currency: USD
                          event_revenue_usd: 5
                        min_time_post_install: 6
                        max_time_post_install: 12
                      - conversion_value: 34
                        events:
                        - event_name: NewDevice
                          mapped_event_name: NewDevice
                          conversion_event: true
                          event_counter: 5
                          event_revenue: 6
                          min_event_revenue: 5.001
                          max_event_revenue: 6
                          event_currency: USD
                          event_revenue_usd: 6
                        - event_name: AchievedLevel1
                          mapped_event_name: AchievedLevel1
                          conversion_event: false
                          event_counter: 6
        '400':
          description: 'Request is malformed'
          content:
            application/json:
              examples:
                Request malformed:
                  value: "{}"
              schema:
                type: object
                properties: {}
        '401':
          description: 'Authentication error'
          content:
            text/plain:
              examples:
                Authentication error:
                  value: "{}"
              schema:
                type: object
                properties: {}
        '404':
          description: 'Server error or resource temporarily not found'
          content:
            text/plain:
              examples:
                Server error:
                  value: "{}"
              schema:
                type: object
                properties: {}
        '429':
          description: 'Exceeded rate limitation'
          content:
            text/plain:
              examples:
                Result:
                  value: Exceeded rate limitation
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CvMapping:
      properties:
        conversion_value:
          description: "Conversion value"
          type: integer
          minimum: 0
          maximum: 63
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        min_time_post_install:
          type: integer
          description: "The lower bound, hours post-install, indicating when the user was last active in the app."
        max_time_post_install:
          type: integer
          description: "The upper bound, hours post-install, indicating when the user was last active in the app"
    Event:
      properties:
        event_name:
          type: string
          description: "Advertiser in-app event name"
        mapped_event_name:
          type: string
          description: "Partner's in-app event name. The advertiser maps event_name to mapped_event_name on a per app basis in AppsFlyer."
        event_counter:
          type: integer
          description: "The number of times the user performed an event."
        conversion_event:
          type: boolean
          description: "In the case of more than one event, if true, this event is a conversion event as defined by the advertiser"
        event_currency:
          type: string
          description: "Currency for event_revenue"
        event_revenue:
          type: integer
          description: "In case of a revenue event, monetary value using event_currency"
        min_event_revenue:
          type: number
          format: float
          description: "The lower bound of the event revenue range"  
        max_event_revenue:
          type: number
          format: float
          description: "The upper bound of the event counter range. Example: To calculate the revenue, (min_event_revenue + max_event_revenue)/2" 
        event_revenue_usd:
          type: number
          format: float
          description: "In case of a revenue event, monetary value" 
        min_event_counter:
          type: integer
          description: "The lower bound of the event counter range" 
        max_event_counter:
          type: integer
          description: "The upper bound of the event counter range. Example: To calcualte the number of ocurrences, roundup (min_event_counter + max_event_counter )/ 2" 


        
                  


    