openapi: 3.0.1
info:
  title: PredictSK Pull API
  version: 1.0.0
servers:
- url: https://hq1.appsflyer.com/api/predict-sk/v1/data/app
  description: Production server
security:
  - Bearer-Authentication: []
paths:
  /{app-id}:
    get:
      summary: PredictSK aggregated report
      description: "The PredictSK aggregated report returns attribution metrics reported by Apple SKAdNetwork (real data) and other data points using the install or postback arrival date. The report is available through Data Locker or the API."
      parameters:
      - name: app-id
        in: path
        description: "The app identifier as found in the AppsFlyer dashboard. Insert it exactly as it displays in the dashboard"
        example: "id123456789"
        required: true
        schema:
          type: string
      - name: start_date
        in: query
        description: "The date type used in the date range bounded by **start_date** and **end_date**\n\n start_date is the lower bound of requested dates\n\n **Note!** Install date differs from postback arrival date.\n\n Expects YYYY-MM-DD format"
        example: "2021-11-06"
        required: true
        schema:
          type: string
      - name: end_date
        in: query
        description: "end_date is the upper bound of requested dates\n\n Maximum number of days per report call: 90 days\n\n Expects YYYY-MM-DD format"
        example: "2021-11-05"
        required: true
        schema:
          type: string
      - name: view_type
        in: query
        description: >
         Filter the installs by type as follows: 
          - `acquisition`: Installs
          - `retargeting`: Redownloads
          - `unified`: Acquisition and redownload combined
           
         Default value is `unified`
        required: false
        schema:
          type: string
          enum:
            - acquisition
            - retargeting 
            - unified
          default: unified
      responses:
        200:
          description: Valid data returned (CSV)
          content: {}
        400:
          description: Bad request - Missing or invalid query parameters
          content: {}
        401:
          description: Unauthorized - Authorization token is missing or invalid. Make sure you use the token correctly
          content: {}
        403:
          description: No permission - You don't have permission to access this report. If you are an analytics partner ask the advertiser to give you permission.
          content: {}
        404:
          description: Not found - Handle any network or firewall-related problems. Make sure that AppsFlyer [IP addresses are allowlisted](https://support.appsflyer.com/hc/en-us/articles/207447093-AppsFlyer-server-IP-address-ranges-allowlisting-)
          content: {}
        429:
          description: Too many requests - Exceeded rate limitation
          content: {}
components:
  securitySchemes:
    Bearer-Authentication:
      type: http
      scheme: bearer
      description: "Authorization HTTP header containing API V2.0 token (Bearer token) is required.\n\n
        The admin [gets the V2 token in the dashboard](https://support.appsflyer.com/hc/en-us/articles/360004562377), go to your email address"
