openapi: 3.0.1
info:
  title: Predict Android Pull API
  version: 1.0.0
servers:
- url: https://hq1.appsflyer.com/api/predict-android/v1.0/data/app
  description: Production server
security:
  - Bearer-Authentication: []
paths:
  /{app-id}:
    get:
      tags:
      - Predict Android aggregated report
      summary: Get report
      description: "The Predict aggregated report returns predicted performance metrics, for Android apps."
      operationId: predict-android-pull-api-get
      parameters:
      - name: app-id
        in: path
        description: "The app identifier as found in the AppsFlyer dashboard. Insert it exactly as it displays in the dashboard"
        example: "com.example.app"
        required: true
        schema:
          type: string
      - name: start_date
        in: query
        description: |
          The date type used in the date range bounded by **start_date** and **end_date**
          start_date is the lower bound of requested dates
          **Note!** Install date differs from postback arrival date.
          Expects `YYYY-MM-DD` format
        example: "2023-11-05"
        required: true
        schema:
          type: string
          pattern: ^\d{4}\-\d{2}\-\d{2}$
      - name: end_date
        in: query
        description: | 
          end_date is the upper bound of requested dates
          Maximum number of days per report call: 90 days
          Expects `YYYY-MM-DD` format"
        example: "2023-11-06"
        required: true
        schema:
          type: string
          pattern: ^\d{4}\-\d{2}\-\d{2}$
      responses:
        200:
          description: Valid data returned (CSV)
          content: {}
        400:
          description: Bad request - Missing or invalid query parameters
          content:
            application/json:
              schema:
                type: string
              examples:
                Bad Request:
                  value:
                    {
                      "error": {
                        "status": 400,
                        "code": "BadRequest",
                        "message": "Missing or invalid query parameters. Please make sure to include all required parameters.",
                      }
                    }
        401:
          description: Unauthorized - Authorization token is missing or invalid. Make sure you use the token correctly
          content:
            application/json:
              schema:
                type: string
              examples:
                Unauthorized:
                  value:
                    {
                      "error": {
                        "status": 401,
                        "code": "Unauthorized",
                        "message": "Authorization token is missing or invalid. Make sure you use the token correctly"
                      }
                    }
        403:
          description: No permission - You don't have permission to access this report.
          content:
            application/json:
              schema:
                type: string
              examples:
                Forbidden:
                  value:
                    {
                      "error": {
                        "status": 403,
                        "code": "Forbidden",
                        "message": "You don't have permission to access this report. If you are an analytics partner ask the advertiser to give you permission."
                      }
                    }
        404:
          description: Not found - Handle any network or firewall-related problems. Make sure that AppsFlyer [IP addresses are allowlisted](https://support.appsflyer.com/hc/en-us/articles/207447093-AppsFlyer-server-IP-address-ranges-allowlisting-)
          content:
            application/json:
              schema:
                type: string
              examples:
                Not Found:
                  value:
                    {
                      "error": {
                        "status": 404,
                        "code": "NotFound",
                        "message": "The requested URL was not found. Handle any network problems and make sure you used the correct app-id in the query"
                      }
                    }
        429:
          description: Too many requests - Exceeded rate limitation
          content:
            application/json:
              schema:
                type: string
              examples:
                Too Many Requests:
                  value:
                    {
                      "error": {
                        "status": 429,
                        "code": "TooManyRequests",
                        "message": "Too many requests - Exceeded rate limitation"
                      }
                    }
components:
  securitySchemes:
    Bearer-Authentication:
      type: http
      scheme: bearer
      description: |
        Authorization HTTP header containing API V2.0 token (Bearer token) is required.
        The admin [gets the V2 token in the dashboard](https://support.appsflyer.com/hc/en-us/articles/360004562377), go to your email address
