openapi: 3.0.1
info:
  title: AdRevenue Account Integrations API
  description: API for configuring or changing partner integrations.
  version: 1.0.0
servers:
  - url: https://hq1.appsflyer.com/api/adrevenue/v1.0
    description: api server - production
security:
  - bearerAuth: []
tags:
  - name: AdRevenue Account Integrations API

paths:
  /integrations:
    post:
      tags:
        - AdRevenue Account Integrations API
      summary: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/integration'
        required: true
      responses:
        '200':
          description:  CHANGE ME
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          description: invalid request or schema
        '422':
          description: invalid request or schema
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    integration:
      title: 'An array describing the ad revenue integrations for which all the hierarchical data is defined.'
      required:
        - app_id
        - network
        - credentials
        - products
      type: 'object'
      properties:
        app_id:
          type: string
          description: The `app_id` for which the integration is defined
        network:
          type: string
        credentials:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/AdColony_cred'
              - $ref: '#/components/schemas/AdMost_cred'
        products:
          type: array
          items:
            $ref: '#/components/schemas/product'
    product:
      description: The products block lists the products & integration types that the customer wishes to configure for the defined partner `network`.
      required:
        - name
        - enabled
      type: object
      properties:
        name:
          type: string
        enabled:
          type: string
          enum:
            - true
            - false
          example: true
        source_event:
          type: string
        event_name:
          type: string
    AdColony_cred:
      type: object
      properties:
        app_id:
          type: string
        api_key:
          type: string
    AdMost_cred:
      type: object
      properties:
        app_id:
          type: string
        token:
          type: string
    

    